import { z } from "zod";

// Pays francophones et importants en priorité, puis tous les pays ONU par ordre alphabétique
export const COUNTRY_OPTIONS = [
  // — Prioritaires —
  "France",
  "Belgique",
  "Suisse",
  "Luxembourg",
  "Monaco",
  "Canada",
  "Maroc",
  "Tunisie",
  "Algérie",
  "Sénégal",
  "Côte d'Ivoire",
  "Cameroun",
  "République démocratique du Congo",
  "Madagascar",
  "Allemagne",
  "Espagne",
  "Italie",
  "Portugal",
  "Pays-Bas",
  "Royaume-Uni",
  "États-Unis",
  // — Tous les pays ONU (A-Z) —
  "Afghanistan",
  "Afrique du Sud",
  "Albanie",
  "Andorre",
  "Angola",
  "Antigua-et-Barbuda",
  "Arabie saoudite",
  "Argentine",
  "Arménie",
  "Australie",
  "Autriche",
  "Azerbaïdjan",
  "Bahamas",
  "Bahreïn",
  "Bangladesh",
  "Barbade",
  "Bélarus",
  "Belize",
  "Bénin",
  "Bhoutan",
  "Bolivie",
  "Bosnie-Herzégovine",
  "Botswana",
  "Brésil",
  "Brunei",
  "Bulgarie",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodge",
  "Centrafrique",
  "Chili",
  "Chine",
  "Chypre",
  "Colombie",
  "Comores",
  "Congo",
  "Corée du Nord",
  "Corée du Sud",
  "Costa Rica",
  "Croatie",
  "Cuba",
  "Danemark",
  "Djibouti",
  "Dominique",
  "Égypte",
  "Émirats arabes unis",
  "Équateur",
  "Érythrée",
  "Estonie",
  "Eswatini",
  "Éthiopie",
  "Fidji",
  "Finlande",
  "Gabon",
  "Gambie",
  "Géorgie",
  "Ghana",
  "Grèce",
  "Grenade",
  "Guatemala",
  "Guinée",
  "Guinée équatoriale",
  "Guinée-Bissau",
  "Guyana",
  "Haïti",
  "Honduras",
  "Hongrie",
  "Îles Marshall",
  "Îles Salomon",
  "Inde",
  "Indonésie",
  "Irak",
  "Iran",
  "Irlande",
  "Islande",
  "Israël",
  "Jamaïque",
  "Japon",
  "Jordanie",
  "Kazakhstan",
  "Kenya",
  "Kirghizistan",
  "Kiribati",
  "Koweït",
  "Laos",
  "Lesotho",
  "Lettonie",
  "Liban",
  "Liberia",
  "Libye",
  "Liechtenstein",
  "Lituanie",
  "Macédoine du Nord",
  "Malaisie",
  "Malawi",
  "Maldives",
  "Mali",
  "Malte",
  "Maurice",
  "Mauritanie",
  "Mexique",
  "Micronésie",
  "Moldavie",
  "Mongolie",
  "Monténégro",
  "Mozambique",
  "Myanmar",
  "Namibie",
  "Nauru",
  "Népal",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "Norvège",
  "Nouvelle-Zélande",
  "Oman",
  "Ouganda",
  "Ouzbékistan",
  "Pakistan",
  "Palaos",
  "Palestine",
  "Panama",
  "Papouasie-Nouvelle-Guinée",
  "Paraguay",
  "Pérou",
  "Philippines",
  "Pologne",
  "Qatar",
  "République dominicaine",
  "République tchèque",
  "Roumanie",
  "Russie",
  "Rwanda",
  "Saint-Kitts-et-Nevis",
  "Saint-Vincent-et-les-Grenadines",
  "Sainte-Lucie",
  "Samoa",
  "São Tomé-et-Príncipe",
  "Serbie",
  "Seychelles",
  "Sierra Leone",
  "Singapour",
  "Slovaquie",
  "Slovénie",
  "Somalie",
  "Soudan",
  "Soudan du Sud",
  "Sri Lanka",
  "Suède",
  "Suriname",
  "Syrie",
  "Tadjikistan",
  "Tanzanie",
  "Tchad",
  "Thaïlande",
  "Timor oriental",
  "Togo",
  "Tonga",
  "Trinité-et-Tobago",
  "Turkménistan",
  "Turquie",
  "Tuvalu",
  "Ukraine",
  "Uruguay",
  "Vanuatu",
  "Vatican",
  "Venezuela",
  "Viêt Nam",
  "Yémen",
  "Zambie",
  "Zimbabwe",
] as const;

// Mapping pays → nationalité (même ordre que COUNTRY_OPTIONS)
export const COUNTRY_TO_NATIONALITY: Record<string, string> = {
  "France": "Française", "Belgique": "Belge", "Suisse": "Suisse", "Luxembourg": "Luxembourgeoise",
  "Monaco": "Monégasque", "Canada": "Canadienne", "Maroc": "Marocaine", "Tunisie": "Tunisienne",
  "Algérie": "Algérienne", "Sénégal": "Sénégalaise", "Côte d'Ivoire": "Ivoirienne",
  "Cameroun": "Camerounaise", "République démocratique du Congo": "Congolaise", "Madagascar": "Malgache",
  "Allemagne": "Allemande", "Espagne": "Espagnole", "Italie": "Italienne", "Portugal": "Portugaise",
  "Pays-Bas": "Néerlandaise", "Royaume-Uni": "Britannique", "États-Unis": "Américaine",
  "Afghanistan": "Afghane", "Afrique du Sud": "Sud-africaine", "Albanie": "Albanaise",
  "Andorre": "Andorrane", "Angola": "Angolaise", "Antigua-et-Barbuda": "Antiguaise",
  "Arabie saoudite": "Saoudienne", "Argentine": "Argentine", "Arménie": "Arménienne",
  "Australie": "Australienne", "Autriche": "Autrichienne", "Azerbaïdjan": "Azerbaïdjanaise",
  "Bahamas": "Bahamienne", "Bahreïn": "Bahreïnienne", "Bangladesh": "Bangladaise",
  "Barbade": "Barbadienne", "Bélarus": "Biélorusse", "Belize": "Bélizienne",
  "Bénin": "Béninoise", "Bhoutan": "Bhoutanaise", "Bolivie": "Bolivienne",
  "Bosnie-Herzégovine": "Bosnienne", "Botswana": "Botswanaise", "Brésil": "Brésilienne",
  "Brunei": "Brunéienne", "Bulgarie": "Bulgare", "Burkina Faso": "Burkinabè",
  "Burundi": "Burundaise", "Cabo Verde": "Cap-verdienne", "Cambodge": "Cambodgienne",
  "Centrafrique": "Centrafricaine", "Chili": "Chilienne", "Chine": "Chinoise",
  "Chypre": "Chypriote", "Colombie": "Colombienne", "Comores": "Comorienne",
  "Congo": "Congolaise", "Corée du Nord": "Nord-coréenne", "Corée du Sud": "Sud-coréenne",
  "Costa Rica": "Costaricaine", "Croatie": "Croate", "Cuba": "Cubaine",
  "Danemark": "Danoise", "Djibouti": "Djiboutienne", "Dominique": "Dominiquaise",
  "Égypte": "Égyptienne", "Émirats arabes unis": "Émirienne", "Équateur": "Équatorienne",
  "Érythrée": "Érythréenne", "Estonie": "Estonienne", "Eswatini": "Swazie",
  "Éthiopie": "Éthiopienne", "Fidji": "Fidjienne", "Finlande": "Finlandaise",
  "Gabon": "Gabonaise", "Gambie": "Gambienne", "Géorgie": "Géorgienne",
  "Ghana": "Ghanéenne", "Grèce": "Grecque", "Grenade": "Grenadienne",
  "Guatemala": "Guatémaltèque", "Guinée": "Guinéenne", "Guinée équatoriale": "Équato-guinéenne",
  "Guinée-Bissau": "Bissau-guinéenne", "Guyana": "Guyanienne", "Haïti": "Haïtienne",
  "Honduras": "Hondurienne", "Hongrie": "Hongroise", "Îles Marshall": "Marshallaise",
  "Îles Salomon": "Salomonaise", "Inde": "Indienne", "Indonésie": "Indonésienne",
  "Irak": "Irakienne", "Iran": "Iranienne", "Irlande": "Irlandaise",
  "Islande": "Islandaise", "Israël": "Israélienne", "Jamaïque": "Jamaïcaine",
  "Japon": "Japonaise", "Jordanie": "Jordanienne", "Kazakhstan": "Kazakhe",
  "Kenya": "Kényane", "Kirghizistan": "Kirghize", "Kiribati": "Kiribatienne",
  "Koweït": "Koweïtienne", "Laos": "Laotienne", "Lesotho": "Lésothane",
  "Lettonie": "Lettone", "Liban": "Libanaise", "Liberia": "Libérienne",
  "Libye": "Libyenne", "Liechtenstein": "Liechtensteinoise", "Lituanie": "Lituanienne",
  "Macédoine du Nord": "Macédonienne", "Malaisie": "Malaisienne", "Malawi": "Malawienne",
  "Maldives": "Maldivienne", "Mali": "Malienne", "Malte": "Maltaise",
  "Maurice": "Mauricienne", "Mauritanie": "Mauritanienne", "Mexique": "Mexicaine",
  "Micronésie": "Micronésienne", "Moldavie": "Moldave", "Mongolie": "Mongole",
  "Monténégro": "Monténégrine", "Mozambique": "Mozambicaine", "Myanmar": "Birmane",
  "Namibie": "Namibienne", "Nauru": "Nauruane", "Népal": "Népalaise",
  "Nicaragua": "Nicaraguayenne", "Niger": "Nigérienne", "Nigeria": "Nigériane",
  "Norvège": "Norvégienne", "Nouvelle-Zélande": "Néo-zélandaise", "Oman": "Omanaise",
  "Ouganda": "Ougandaise", "Ouzbékistan": "Ouzbèke", "Pakistan": "Pakistanaise",
  "Palaos": "Palaoise", "Palestine": "Palestinienne", "Panama": "Panaméenne",
  "Papouasie-Nouvelle-Guinée": "Papouane-néo-guinéenne", "Paraguay": "Paraguayenne",
  "Pérou": "Péruvienne", "Philippines": "Philippine", "Pologne": "Polonaise",
  "Qatar": "Qatarienne", "République dominicaine": "Dominicaine", "République tchèque": "Tchèque",
  "Roumanie": "Roumaine", "Russie": "Russe", "Rwanda": "Rwandaise",
  "Saint-Kitts-et-Nevis": "Kittitienne", "Saint-Vincent-et-les-Grenadines": "Vincentaise",
  "Sainte-Lucie": "Saint-Lucienne", "Samoa": "Samoane", "São Tomé-et-Príncipe": "Santoméenne",
  "Serbie": "Serbe", "Seychelles": "Seychelloise", "Sierra Leone": "Sierra-léonaise",
  "Singapour": "Singapourienne", "Slovaquie": "Slovaque", "Slovénie": "Slovène",
  "Somalie": "Somalienne", "Soudan": "Soudanaise", "Soudan du Sud": "Sud-soudanaise",
  "Sri Lanka": "Sri-lankaise", "Suède": "Suédoise", "Suriname": "Surinamaise",
  "Syrie": "Syrienne", "Tadjikistan": "Tadjike", "Tanzanie": "Tanzanienne",
  "Tchad": "Tchadienne", "Thaïlande": "Thaïlandaise", "Timor oriental": "Est-timoraise",
  "Togo": "Togolaise", "Tonga": "Tongienne", "Trinité-et-Tobago": "Trinidadienne",
  "Turkménistan": "Turkmène", "Turquie": "Turque", "Tuvalu": "Tuvaluane",
  "Ukraine": "Ukrainienne", "Uruguay": "Uruguayenne", "Vanuatu": "Vanuatuane",
  "Vatican": "Vaticane", "Venezuela": "Vénézuélienne", "Viêt Nam": "Vietnamienne",
  "Yémen": "Yéménite", "Zambie": "Zambienne", "Zimbabwe": "Zimbabwéenne",
};

// Liste des nationalités dans le même ordre que COUNTRY_OPTIONS
export const NATIONALITY_OPTIONS = COUNTRY_OPTIONS.map((c) => COUNTRY_TO_NATIONALITY[c] ?? c);

/** Retourne la nationalité correspondant à un pays */
export function getNationalityForCountry(country: string): string {
  return COUNTRY_TO_NATIONALITY[country] ?? "";
}

export const LEAD_SOURCE_OPTIONS = [
  "Bouche à oreille",
  "Google",
  "Réseaux sociaux",
  "Passage en boutique",
  "Recommandation",
  "Publicité",
  "Autre",
] as const;

export const DOCUMENT_TYPE_OPTIONS = [
  { value: "cni", label: "Carte nationale d'identité" },
  { value: "passeport", label: "Passeport" },
  { value: "titre_sejour", label: "Titre de séjour" },
  { value: "permis_conduire", label: "Permis de conduire" },
] as const;

export const clientSchema = z.object({
  civility: z.enum(["M", "Mme"], { message: "La civilité est requise" }),
  first_name: z.string().min(1, "Le prénom est requis").max(100, "100 caractères maximum"),
  last_name: z.string().min(1, "Le nom est requis").max(100, "100 caractères maximum"),
  maiden_name: z.string().max(100).optional().or(z.literal("")),
  email: z.string().min(1, "L'email est requis").email("Format email invalide"),
  phone: z.string().max(20).optional().or(z.literal("")),
  address: z.string().min(1, "L'adresse est requise").max(255, "255 caractères maximum"),
  city: z.string().min(1, "La ville est requise").max(100, "100 caractères maximum"),
  postal_code: z.string().min(1, "Le code postal est requis").max(10, "10 caractères maximum"),
  country: z.string().min(1, "Le pays est requis").max(100, "100 caractères maximum"),
  lead_source: z.enum(LEAD_SOURCE_OPTIONS).optional().or(z.literal("")),
  notes: z.string().optional().or(z.literal("")),
});

export type ClientFormData = z.infer<typeof clientSchema>;

export const identityDocumentSchema = z.object({
  document_type: z.enum(["cni", "passeport", "titre_sejour", "permis_conduire"], {
    message: "Le type de document est requis",
  }),
  document_number: z.string().min(1, "Le numéro est requis").max(50, "50 caractères maximum"),
  issue_date: z.string().optional().or(z.literal("")),
  expiry_date: z.string().optional().or(z.literal("")),
  nationality: z.string().optional().or(z.literal("")),
  is_primary: z.boolean().default(true),
});

export type IdentityDocumentFormData = z.infer<typeof identityDocumentSchema>;
